export const WEBSITE_KNOWLEDGE_MESSAGES = {
  connectTitle: "Website Knowledge Sync",
  connectDescription:
    "Enter your website URL. OrzuX scans pages and builds your AI knowledge base automatically.",
  siteUrlLabel: "Website address",
  siteUrlPlaceholder: "https://yourcompany.com",
  saveAndSync: "Save & sync now",
  syncNow: "Sync now",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved",
  syncSuccess: "Website knowledge updated for AI replies.",
  syncInProgress: "Sync is already running. Please wait.",
  setupRequired: "Save your website URL first.",
  noPagesFound: "Could not read any pages from this website. Check the URL is public.",
  noEntriesExtracted:
    "Pages were scanned but no usable business information was found.",
  autoSyncLabel: "Automatic sync when the site changes",
  autoSyncHint:
    "OrzuX re-scans your site on a schedule and refreshes AI knowledge entries.",
  intervalLabel: "Sync schedule",
  lastSynced: "Last sync",
  nextSync: "Next auto sync",
  never: "Never",
  pagesIndexed: "Pages scanned",
  entriesSynced: "Knowledge entries",
  statusReady: "Ready",
  statusSyncing: "Syncing…",
  statusError: "Error",
  statusIdle: "Not synced yet",
  openKnowledgeBase: "View knowledge base",
  aiUsageNote:
    "Synced knowledge is used automatically in WhatsApp, Instagram, Telegram, Email follow-ups, and chat AI replies.",
  noBusinessTitle: "Business profile required",
  noBusinessDescription: "Complete business settings before syncing your website.",
  notConfigured: "Supabase is not configured.",
  geminiRequired:
    "Add GEMINI_API_KEY or ANTHROPIC_API_KEY to scan and organize website knowledge.",
  genericError: "Something went wrong. Please try again.",
  disconnect: "Remove website sync",
  disconnectSuccess: "Website knowledge sync removed.",
} as const;
